apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: guestbook
  annotations:
    avp.kubernetes.io/path: apps/data/eai-vault/applications/canary/ykoer-test
stringData:
  password: <password>
